apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pruthvi-sample-app-route
  namespace: openshift-ztp
spec:
  to:
    kind: Service
    name: pruthvi-sample-app-service
  port:
    targetPort: 8080
  tls:
    termination: edge
