apiVersion: v1
kind: Secret
metadata:
  name: pullsecret
  namespace: ocp2
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '<copy from bastion/config.json/should have both mirror registry auth and registry.redhat.io + other auths>'
