apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeDiscoveryResult
metadata:
  creationTimestamp: "2025-06-08T18:35:53Z"
  generation: 1
  labels:
    discovery-result-node: worker2.ocp.pdlab.sg
  name: discovery-result-worker2.ocp.pdlab.sg
  namespace: openshift-local-storage
  ownerReferences:
  - apiVersion: local.storage.openshift.io/v1alpha1
    kind: LocalVolumeDiscovery
    name: auto-discover-devices
    uid: 198af855-fa9b-462d-bbc6-9330b8baff95
  resourceVersion: "1450729"
  uid: c5112ac3-4824-4a48-bd5e-1509aeb8b93f
spec:
  nodeName: 
    - worker1.ocp.lab.sg
    - workerX.ocp.lab.sg
